### ISSUE TITLE
Training a new model

### ISSUE THREAD

**Issue by theandrepo** [zamgi/lingvo--Ner-en#1]
Hello,

really good work.
Do you have any chance to tell how to train a new language ? 
I assume we need to feed examples of labelled sentences : which annotation format ? and how to (series of steps).

Thanks in advance.

**Comment by zamgi** [comment]
Hi,
soon I planning to change the repositories to net-core version.
maybe/possible, I'll give an example of learning a new language. 

annotation format is something like a Inside–outside–beginning (see https://en.wikipedia.org/wiki/Inside%E2%80%93outside%E2%80%93beginning_(tagging))

**Comment by zamgi** [comment]
Hi, 
not now. may be later.
